### ISSUE TITLE
Невозможно отметить фильм как просмотренный

### ISSUE THREAD

**Issue by servint** [quarckster/kodi.kino.pub#131]
Ошибка. Но на самом деле пометка "просмотрено/не просмотрено" ставится. Необходимо выйти на уровень вверх и заново зайти в папку. Kodi 18.8 на Andoid TV.

**Comment by quarckster** [comment]
Пожалуйста опишите по пунктам список действий, которые вы делаете и приложите логи.

**Comment by rsmime** [comment]
Аналогичная проблема, при попытке отметить фильм как просмотренный всплывает сообщение об ошибке. Вот лог

`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ValueError'>
Error Contents: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/kodi/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
    plugin.run()
  File "/home/kodi/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 76, in run
    self.routing.dispatch(self.path)
  File "/home/kodi/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 63, in dispatch
    view_func(**kwargs)
  File "/home/kodi/.kodi/addons/video.kino.pub/resources/lib/main.py", line 403, in toggle_watched
    plugin.client("watching/marktime").get(data=data)
  File "/home/kodi/.kodi/addons/video.kino.pub/resources/lib/client.py", line 50, in get
    return self._make_request(request)
  File "/home/kodi/.kodi/addons/video.kino.pub/resources/lib/client.py", line 40, in _make_request
    response = json.loads(response.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-->End of Python script error report<--`

Причина в том, что в ответе сервера отсутствует тело:

`json.loads(response.read()) => json.loads("") => ValueError`

Ссылка на API https://kinoapi.com/api_watching.html#api-watching-marktime

**Comment by quarckster** [comment]
Fixed in #150
