### ISSUE TITLE
не проходит регистрация устройства

### ISSUE THREAD

**Issue by fuchunic** [quarckster/kodi.kino.pub#135]
При активации получаем ошибку в логе:

Kodi: 9.2.4
Устройство Raspberry 3.
дистрибутив: LibreELEC (official)

`
2020-10-06 21:26:28.913 T:1790935936  NOTICE: [video.kino.pub]: sending payload {u'client_secret': u'cgg3gtifu46urtfp2zp1nqtba0k2ezxh', u'grant_type': u'device_code', u'client_id': u'xbmc'} to oauth api
2020-10-06 21:26:29.180 T:1790935936  NOTICE: [video.kino.pub]: getting a new device token
2020-10-06 21:26:29.180 T:1790935936  NOTICE: [video.kino.pub]: sending payload {u'code': u'tkas7bm15kf9u7c4fz8j29anx6gbxfy9', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtba0k2ezxh', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
2020-10-06 21:26:33.087 T:1790935936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'Auth' object has no attribute 'request'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 76, in run
                                                self.routing.dispatch(self.path)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 63, in dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 74, in login
                                                plugin.auth.get_token()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 207, in get_token
                                                self._activate()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 199, in _activate
                                                self._verify_device_code(resp["refresh_interval"], resp["device_code"])
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 168, in _verify_device_code
                                                self._get_device_token(device_code)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 128, in _get_device_token
                                                resp = self._make_request(payload)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 98, in _make_request
                                                return self.request(payload)
                                            AttributeError: 'Auth' object has no attribute 'request'
                                            -->End of Python script error report<--
2020-10-06 21:26:33.179 T:1790935936 WARNING: CPythonInvoker(4, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2020-10-06 21:28:24.474 T:1936839232   ERROR: Control 1000 in window 13000 has been asked to focus, but it can't
2020-10-06 21:28:24.481 T:1936839232  NOTICE: LoadJpeg: unable to load /usr/share/kodi/addons/service.libreelec.settings/resources/skins/Default/media/bg.jpg
2020-10-06 21:28:43.274 T:1936839232   ERROR: Control 1200 in window 13000 has been asked to focus, but it can't
`

**Comment by flameshikari** [comment]
Та же проблема.

Kodi 18.7
Raspberry Pi 4B
Raspbian

**Comment by NattyWalrus** [comment]
`2020-10-07 14:03:52.502 T:1636770688  NOTICE: [video.kino.pub]: sending payload {u'client_secret': 123', u'grant_type': u'device_code', u'client_id': u'xbmc'} to oauth api
2020-10-07 14:03:52.667 T:1636770688  NOTICE: [video.kino.pub]: getting a new device token                                                                                                                
2020-10-07 14:03:52.668 T:1636770688  NOTICE: [video.kino.pub]: sending payload {u'code': u'123', u'client_secret': 123', u'grant_type': u'device_token', u'client_id': u'xbmc'} to
2020-10-07 14:03:52.763 T:1636770688   FATAL: [video.kino.pub]: oauth request error; status: 503; message:                                                                                                                                     
2020-10-07 14:03:52.766 T:1636770688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                                                              
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                                                                                   
                                            Error Type: <type 'exceptions.UnboundLocalError'>                                                                                                                                                  
                                            Error Contents: local variable 'response' referenced before assignment                                                                                                                             
                                            Traceback (most recent call last):                                                                                                                                                                 
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>                                                                                                                        
                                                plugin.run()                                                                                                                                                                                   
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 76, in run                                                                                                             
                                                self.routing.dispatch(self.path)                                                                                                                                                               
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 63, in dispatch                                                                                                       
                                                view_func(**kwargs)                                                                                                                                                                            
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 74, in login                                                                                                             
                                                plugin.auth.get_token()                                                                                                                                                                        
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 207, in get_token                                                                                                        
                                                self._activate()                                                                                                                                                                               
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 199, in _activate                                                                                                        
                                                self._verify_device_code(resp["refresh_interval"], resp["device_code"])                                                                                                                        
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 168, in _verify_device_code                                                                                              
                                                self._get_device_token(device_code)                                                                                                                                                            
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 128, in _get_device_token                                                                                                
                                                resp = self._make_request(payload)                                                                                                                                                             
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 103, in _make_request                                                                                                    
                                                notice("...... ............ .............. {}".format(response["status"]), "...................... ............")                                                                              
                                            UnboundLocalError: local variable 'response' referenced before assignment                                                                                                                          
                                            -->End of Python script error report<--                                                                                                                                                            
2020-10-07 14:03:52.881 T:1636770688 WARNING: CPythonInvoker(7, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up.`

**Comment by quarckster** [comment]
@NattyWalrus 
Переоткрываю баг

**Comment by NattyWalrus** [comment]
@quarckster , если что - я открыл новую проблему
https://github.com/quarckster/kodi.kino.pub/issues/137
