### ISSUE TITLE
ПОИСК: KODI 19.0-Matrix beta2 x64 + 3.0 + W10Pro20H2

### ISSUE THREAD

**Issue by eGreyWolf** [quarckster/kodi.kino.pub#147]
Спасибо, всё нравится! Но, почему то, валится функция «Поиска». Поиск не работает ни глобальный, ни среди фильмов: «Ошибка kino.pub»
Еще, пользуясь случаем, добавлю, что с экрана не доступна кириллица: вместо нее символы в юникоде. Но с клавиатуры ввод корректный.
В логах, увы, следов не нашел. Или не могу найти.
Спасибо!

**Comment by eGreyWolf** [comment]
**Доброго времени, уважаемый коллега!** 
Спасибо, что поремонтировали, но, всё же, у меня поиск так и не работает.
Возможно из-за этого:
"`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'`
Искал слово «ABBA», латиницей. Юникод вместо кириллицы в клавиатуре поиска, остался.

Вот от начала запуска Вашего аддона до ошиюбки, блок целиком:
`2020-12-23 20:53:43.238 T:5208     INFO <general>: Loading skin file: AddonBrowser.xml, load type: KEEP_IN_MEMORY
2020-12-23 20:54:04.889 T:5208     INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2020-12-23 20:54:04.932 T:7312     INFO <general>: initializing python engine.
2020-12-23 20:54:05.087 T:7312     INFO <general>: CPythonInvoker(1, C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py): script successfully run
2020-12-23 20:54:05.099 T:7312     INFO <general>: Python interpreter stopped
2020-12-23 20:54:08.200 T:1952     INFO <general>: initializing python engine.
2020-12-23 20:54:08.352 T:1952     INFO <general>: CPythonInvoker(2, C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py): script successfully run
2020-12-23 20:54:08.366 T:1952     INFO <general>: Python interpreter stopped
2020-12-23 20:54:10.285 T:5504     INFO <general>: initializing python engine.
2020-12-23 20:54:10.440 T:5208     INFO <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2020-12-23 20:54:18.634 T:5504     INFO <general>: [video.kino.pub]: ABBA
2020-12-23 20:54:18.634 T:5504     INFO <general>: CPythonInvoker(3, C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py): script successfully run
2020-12-23 20:54:18.671 T:9544     INFO <general>: initializing python engine.
2020-12-23 20:54:18.675 T:5504     INFO <general>: Python interpreter stopped
2020-12-23 20:54:18.829 T:9544    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\plugin.py", line 75, in run
                                                       self.routing.dispatch(self.path)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\routing.py", line 63, in dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\main.py", line 230, in search_results
                                                       plugin.search_history.save(plugin.kwargs["title"].decode("utf8"))
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
                                                   
2020-12-23 20:54:18.851 T:9544     INFO <general>: Python interpreter stopped
2020-12-23 20:54:18.858 T:11248   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://video.kino.pub/search/all/results/?title=ABBA
2020-12-23 20:54:18.867 T:5208    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/search/all/results/?title=ABBA) failed
2020-12-23 20:54:18.871 T:12096    INFO <general>: initializing python engine.
2020-12-23 20:54:19.019 T:12096    INFO <general>: CPythonInvoker(5, C:\Users\User\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py): script successfully run
2020-12-23 20:54:19.032 T:12096    INFO <general>: Python interpreter stopped`

**Comment by quarckster** [comment]
Я ещё не выпустил новую версию, ошибка исправлена в мастере https://github.com/quarckster/kodi.kino.pub/blob/master/src/resources/lib/main.py#L228

**Comment by eGreyWolf** [comment]
Спасибо, Дмитрий!
Мне с "мастером" без Мастера, увы, не разобраться... Подожду, значит, Вашего релиза.
Еще раз спасибо и извините!

**Comment by eGreyWolf** [comment]
Доброго времени, Мастер!
ДоЗадам еще ДВА вопроса, с Вашего позволения:
1. Не получится ли выпустить новую версию с исправлением к НГ?
Хочется использовать плагин полноценно как раз в эти длинные НГ-каникулы;
2. О том, что у Вас получилось, не могли бы Вы уведомить меня отдельно?
Спасибо

**Comment by quarckster** [comment]
1. Новая версия выпущена https://github.com/quarckster/kodi.kino.pub/releases
2. Не мог бы, но можно автоматически обновлять плагин, как это сделать написано в README.

**Comment by eGreyWolf** [comment]
Спасибо, в очередной раз!
