### ISSUE TITLE
Отметка просмотрено/не просмотрено: не обновляется значок

### ISSUE THREAD

**Issue by servint** [quarckster/kodi.kino.pub#151]
Отметка сама по себе ставится, но значок рядом с названием фильма / серии не меняется, а остается прежним. Чтобы увидеть актуальный значок нужно сделать шаг назад (выйти на меню вверх) и снова зайти туда, где находится фильм / серия. Тогда значок уже актуальный. 

**Update:** иконка не обновляется только на фильмах, добавленных в свои папки (избранное). Иногда нужно выйти из приложения и зайти обратно, чтобы увидеть актуальную иконку о просмотре.

**Comment by VyacheslavTeplyakov** [comment]
Не только.
Просмотренные серии в сериалах вообще не отмечаются. Даже если зайти туда сюда. Руками через меню пометка ставится.

**Comment by Gepar** [comment]
Дополню:
- не отмечаеются просмотренные фильмы/серии сериалов
- не трекается сколько было просмотренно
- в недосмотренные не попадают недосмотренные через коди фильмы
При этом если начать смотреть из браузера а потом сесть за тв через коди то он предложит продолжить с последнего места куда досмотрел, так же он показывает фильмы просмотренные и недосмотренные с браузера.
Похоже плагин умеет получать и парсить информацию с сервера о статусах/просмотре, но не умеет отправлять её.

**Comment by ffoxin** [comment]
> Дополню:
> 
> * не отмечаеются просмотренные фильмы/серии сериалов
> * не трекается сколько было просмотренно
> * в недосмотренные не попадают недосмотренные через коди фильмы
>   При этом если начать смотреть из браузера а потом сесть за тв через коди то он предложит продолжить с последнего места куда досмотрел, так же он показывает фильмы просмотренные и недосмотренные с браузера.
>   Похоже плагин умеет получать и парсить информацию с сервера о статусах/просмотре, но не умеет отправлять её.

1 - есть какая-то проблема, тоже заметил, пытался пофиксить, но сходу не получилось, надо будет еще посидеть
2 - тут сложно что-то придумать. инфу эту может отправить только плагин, не сам коди, а в процессе просмотра коди никак не взаимодействует с плагином. нужен какой-то механизм периодического запуска/проверки сколько пользователь посмотрел фильма, но я не знаю, есть ли что-то такое в коди
3 - тут аналогично 2 пункту. по сути при начале просмотра можно отослать инфу, что пользователь начал смотреть такой-то фильм. но вот дальше проблема: статус просмотра не будет обновляться, потому что кто-то должен дернуть плагин "смотри, мы уже посмотрели 10 минут фильма, отправь это на сервер", а такого сейчас нет

**Comment by Gepar** [comment]
пока плагин (или коди?) будет пытаться загрузить все звуковые дорожки сразу из-за чего сервер будет ему отвечать временами 502й и он будет виснуть пользоваться им нереально, в итоге вернулся на приложение под андроид.

**Comment by stavultras** [comment]
Дополню: При попытке поменять просмотрено/не просмотрено вылезает вот такой баг в логах:
```
2022-08-31 20:13:59.028 T:14888    INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching/toggle?id=81577&season=1&video=2
2022-08-31 20:13:59.552 T:14888    INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching/marktime?id=81577&season=1&video=2&time=0
2022-08-31 20:13:59.942 T:14888   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\plugin.py", line 81, in run
                                                       self.routing.dispatch(self.path)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\routing.py", line 62, in dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\main.py", line 396, in toggle_watched
                                                       plugin.client("watching/marktime").get(data=data)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\client.py", line 50, in get
                                                       return self._make_request(request)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\video.kino.pub\resources\lib\client.py", line 41, in _make_request
                                                       if response["status"] == 200:
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2022-08-31 20:13:59.955 T:14888    INFO <general>: Python interpreter stopped
2022-08-31 20:13:59.979 T:14524   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://video.kino.pub/toggle_watched/81577?season=1&video=2
```

**Comment by stavultras** [comment]
P.S: https://api.service-kp.com/v1/watching/marktime?id=81577&season=1&video=2&time=0 возращает null, вместо JSON, но с HTTP кодом 200.

**Comment by stavultras** [comment]
Создал PR: https://github.com/quarckster/kodi.kino.pub/pull/226
Прошу сильно не пинать, Python не знаю от слова совсем.

**Comment by stavultras** [comment]
@servint @VyacheslavTeplyakov проверьте пожалуйста, исправилась ли ваша проблема.
