### ISSUE TITLE
Ошибка в работе 3.0.2

### ISSUE THREAD

**Issue by 4orsa** [quarckster/kodi.kino.pub#167]
Все работало нормально. с 10.02 появились проблеммы на двух KODI на 18 и 19 (две разные машины).
Пробовал перергистрацию не помогает. Да и регистрация проходит раз через раз. 

 CPythonInvoker(1, /storage/.kodi/addons/video.kino.pub/addon.py): script successfully run
2021-02-12 23:14:24.354 T:933      INFO <general>: Python interpreter stopped
2021-02-12 23:14:28.259 T:937      INFO <general>: initializing python engine.
2021-02-12 23:14:28.811 T:937      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/user
2021-02-12 23:14:29.198 T:894      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-02-12 23:14:30.958 T:937      INFO <general>: CPythonInvoker(2, /storage/.kodi/addons/video.kino.pub/addon.py): script successfully run
2021-02-12 23:14:31.226 T:937      INFO <general>: Python interpreter stopped
2021-02-12 23:14:37.048 T:942      INFO <general>: initializing python engine.
2021-02-12 23:14:37.718 T:942      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/items/fresh?type=None
2021-02-12 23:14:38.347 T:942      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69643
2021-02-12 23:15:45.350 T:894      INFO <general>: Samba is idle. Closing the remaining connections
2021-02-12 23:16:48.341 T:942     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'URLError' object has no attribute 'message'
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
                                                     File "/usr/lib/python3.8/http/client.py", line 1255, in request
                                                     File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
                                                     File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
                                                     File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
                                                     File "/usr/lib/python3.8/http/client.py", line 950, in send
                                                     File "/usr/lib/python3.8/http/client.py", line 1417, in connect
                                                     File "/usr/lib/python3.8/http/client.py", line 921, in connect
                                                     File "/usr/lib/python3.8/socket.py", line 808, in create_connection
                                                     File "/usr/lib/python3.8/socket.py", line 796, in create_connection
                                                   TimeoutError: [Errno 110] Connection timed out
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 24, in _make_request
                                                       response = urllib.request.urlopen(request, timeout=timeout)
                                                     File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                     File "/usr/lib/python3.8/urllib/request.py", line 525, in open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
                                                   urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 75, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 62, in dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 137, in items
                                                       render_items(response.items, content_type)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 62, in render_items
                                                       xbmcplugin.addDirectoryItem(plugin.handle, item.url, item.list_item, item.isdir)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 266, in list_item
                                                       li = super(PlayableItem, self).list_item
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 201, in list_item
                                                       video_info=self.video_info,
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 495, in video_info
                                                       "time": self.resume_time,
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 273, in resume_time
                                                       if self.watching_info["time"] == self.watching_info["duration"]:
                                                     File "/usr/lib/python3.8/functools.py", line 967, in __get__
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 504, in watching_info
                                                       return self.plugin.client("watching").get(data={"id": self.item_id})["item"]["videos"][0]
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 50, in get
                                                       return self._make_request(request)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 36, in _make_request
                                                       self.plugin.logger.error(f"{type(e).__name__}. Message: {e.message}")
                                                   AttributeError: 'URLError' object has no attribute 'message'
                                                   -->End of Python script error report<--
                                                   
2021-02-12 23:16:48.356 T:900      INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-02-12 23:16:48.356 T:900      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=Generic,DEV=0"
2021-02-12 23:16:48.365 T:900      INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=Generic,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2021-02-12 23:16:48.366 T:900      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2021-02-12 23:16:48.366 T:900      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
2021-02-12 23:16:48.633 T:942      INFO <general>: Python interpreter stopped
2021-02-12 23:16:48.638 T:941     ERROR <general>: GetDirectory - Error getting plugin://video.kino.pub/items/all/fresh/
2021-02-12 23:16:48.641 T:894     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/items/all/fresh/) failed
2021-02-12 23:17:00.137 T:949      INFO <general>: initializing python engine.
2021-02-12 23:17:00.746 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/items/hot?type=None
2021-02-12 23:17:02.073 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69121
2021-02-12 23:17:02.667 T:949     ERROR <general>: NEWADDON Unknown Video Info Key "time"
2021-02-12 23:17:02.954 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69622
2021-02-12 23:17:03.650 T:949     ERROR <general>: NEWADDON Unknown Video Info Key "time"
2021-02-12 23:17:03.735 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69616
2021-02-12 23:17:04.452 T:949     ERROR <general>: NEWADDON Unknown Video Info Key "time"
2021-02-12 23:17:04.477 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69619
2021-02-12 23:17:05.184 T:949     ERROR <general>: NEWADDON Unknown Video Info Key "time"
2021-02-12 23:17:05.285 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69613
2021-02-12 23:17:05.685 T:949     ERROR <general>: NEWADDON Unknown Video Info Key "time"
2021-02-12 23:17:05.759 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69604
2021-02-12 23:17:06.333 T:949     ERROR <general>: NEWADDON Unknown Video Info Key "time"
2021-02-12 23:17:06.370 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69601
2021-02-12 23:17:07.168 T:949     ERROR <general>: NEWADDON Unknown Video Info Key "time"
2021-02-12 23:17:07.409 T:949      INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=61690
2021-02-12 23:19:16.830 T:949     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'URLError' object has no attribute 'message'
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
                                                     File "/usr/lib/python3.8/http/client.py", line 1255, in request
                                                     File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
                                                     File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
                                                     File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
                                                     File "/usr/lib/python3.8/http/client.py", line 950, in send
                                                     File "/usr/lib/python3.8/http/client.py", line 1417, in connect
                                                     File "/usr/lib/python3.8/http/client.py", line 921, in connect
                                                     File "/usr/lib/python3.8/socket.py", line 808, in create_connection
                                                     File "/usr/lib/python3.8/socket.py", line 796, in create_connection
                                                   TimeoutError: [Errno 110] Connection timed out
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 24, in _make_request
                                                       response = urllib.request.urlopen(request, timeout=timeout)
                                                     File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                     File "/usr/lib/python3.8/urllib/request.py", line 525, in open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
                                                   urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 75, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 62, in dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 137, in items
                                                       render_items(response.items, content_type)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 62, in render_items
                                                       xbmcplugin.addDirectoryItem(plugin.handle, item.url, item.list_item, item.isdir)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 433, in list_item
                                                       li = super(Multi, self).list_item
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 201, in list_item
                                                       video_info=self.video_info,
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 439, in video_info
                                                       return {**super(Multi, self).video_info, "playcount": self.watching_info["status"]}
                                                     File "/usr/lib/python3.8/functools.py", line 967, in __get__
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 184, in watching_info
                                                       return self.plugin.client("watching").get(data={"id": self.item_id})["item"]
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 50, in get
                                                       return self._make_request(request)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 36, in _make_request
                                                       self.plugin.logger.error(f"{type(e).__name__}. Message: {e.message}")
                                                   AttributeError: 'URLError' object has no attribute 'message'
                                                   -->End of Python script error report<--
                                                   
2021-02-12 23:19:16.840 T:900      INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-02-12 23:19:16.840 T:900      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=Generic,DEV=0"
2021-02-12 23:19:16.855 T:900      INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=Generic,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2021-02-12 23:19:16.856 T:900      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2021-02-12 23:19:16.856 T:900      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
2021-02-12 23:19:17.104 T:949      INFO <general>: Python interpreter stopped
2021-02-12 23:19:17.121 T:948     ERROR <general>: GetDirectory - Error getting plugin://video.kino.pub/items/all/hot/
2021-02-12 23:19:17.140 T:894     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/items/all/hot/) failed
2021-02-12 23:19:35.813 T:956      INFO <general>: initializing python engine.
2021-02-12 23:19:35.931 T:956      INFO <general>: CPythonInvoker(5, /usr/share/kodi/addons/service.libreelec.settings/default.py): script successfully run
2021-02-12 23:19:35.988 T:931      INFO <general>: SETTINGS: run # Received openConfigurationWindow
2021-02-12 23:19:36.097 T:956      INFO <general>: Python interpreter stopped
2021-02-12 23:19:36.100 T:894      INFO <general>: Loading skin file: /usr/share/kodi/addons/service.libreelec.settings/resources/skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml, load type: LOAD_ON_GUI_INIT
2021-02-12 23:19:36.161 T:894     ERROR <general>: Control 1000 in window 13001 has been asked to focus, but it can't
2021-02-12 23:19:36.161 T:931      INFO <general>: SETTINGS: run # Waiting
2021-02-12 23:19:59.678 T:894      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-02-12 23:25:38.788 T:900      INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-02-12 23:25:38.789 T:900      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=Generic,DEV=0"
2021-02-12 23:25:38.803 T:900      INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=Generic,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2021-02-12 23:25:38.805 T:900      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2021-02-12 23:25:38.806 T:900      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE

**Comment by quarckster** [comment]
`TimeoutError: [Errno 110] Connection timed out` означает, что что-то с сетью или сервером. Это не проблема плагина.

**Comment by 4orsa** [comment]
А нет связи с каким сервером? Можно определить к чему он стучится?
Плагин для Kodi и Android устройств кардинально по разному работают?
Проблем на мобильном телефоне подключенному к той же сети через Wifi нет (мобильная сеть отключена). Все работает и показывает.

**Comment by quarckster** [comment]
Всё есть в логах, пишите в поддержку в кинопаба.
