### ISSUE TITLE
Error while opening tv show season

### ISSUE THREAD

**Issue by hellvesper** [quarckster/kodi.kino.pub#17]
add-on ver. 2.1.5

Steps:
1. Open "Я смотрю"
2. Chose "Charmed"
3. Select season 4 (5 got same error)

P.S.
Previous seasons works well.

Log:
```
15:15:38.009 T:2770334464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/video.kino.pub/default.py", line 17, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/video.kino.pub/default.py", line 13, in main
                                                addonworker.init()
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 488, in init
                                                ROUTES[request.path](**request.args)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 257, in season_episodes
                                                status = watching_season["episodes"][episode["number"] - 1]["status"]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
15:15:38.231 T:2770334464 WARNING: CPythonInvoker(9, /home/osmc/.kodi/addons/video.kino.pub/default.py): the python script "/home/osmc/.kodi/addons/video.kino.pub/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
15:15:38.295 T:2991907408   ERROR: GetDirectory - Error getting plugin://video.kino.pub/view_season_episodes?id=9029&season_number=4
15:15:38.300 T:2991907408   ERROR: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/view_season_episodes?id=9029&season_number=4) failed
```

All system logs: http://paste.osmc.tv/sojumeyisa

**Comment by quarckster** [comment]
Не могу воспроизвести. Есть ли ещё проблемные сериалы? Просьба проверять на последней версии.
