### ISSUE TITLE
XBian/Raspberry: не работает стриминг через http (но работает через hls)

### ISSUE THREAD

**Issue by sonnydbb** [quarckster/kodi.kino.pub#187]
Привет, это опять я, извините.

Всё прекрасно работает, если в настройках аддона тип стриминга hls.
Поскольку через hls нельзя менять аудиодорожку, переключаю на http – но тогда ни одно видео не открывается.
Единственное исключение – раздел «ТВ», телеканалы стримятся без проблем.

Лог ошибок при попытке открыть фильм:
2021-03-22 19:19:08.067 T:4750     INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/items/69793
2021-03-22 19:19:08.439 T:4750     INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=69793
2021-03-22 19:19:08.888 T:2857     INFO <general>: VideoPlayer::OpenFile: plugin://video.kino.pub/play/69793
2021-03-22 19:19:08.913 T:2857    ERROR <general>: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://cdn.streambox.in/pd/kinopub/aWQ9Mzc2MDE1OzE1NTc4OTIxNDc7MTAzODQyNTg7MTYxNjQzNzE0OCZoPUZWVmg2dHFydFFlc3Z1X1BiQUxmUUEmZT0xNjE2NTIzNTQ4/e/6c/mHjbJTIzLfooznZsZ.mp4?loc=de
2021-03-22 19:19:08.915 T:4756     INFO <general>: Creating InputStream
2021-03-22 19:19:08.941 T:4756    ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
2021-03-22 19:19:08.941 T:4756    ERROR <general>: CCurlFile::Open failed with code 0 for https://cdn.streambox.in/pd/kinopub/aWQ9Mzc2MDE1OzE1NTc4OTIxNDc7MTAzODQyNTg7MTYxNjQzNzE0OCZoPUZWVmg2dHFydFFlc3Z1X1BiQUxmUUEmZT0xNjE2NTIzNTQ4/e/6c/mHjbJTIzLfooznZsZ.mp4?loc=de:
                                                   
2021-03-22 19:19:08.967 T:4756    ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
2021-03-22 19:19:08.967 T:4756    ERROR <general>: CCurlFile::Open failed with code 0 for https://cdn.streambox.in/pd/kinopub/aWQ9Mzc2MDE1OzE1NTc4OTIxNDc7MTAzODQyNTg7MTYxNjQzNzE0OCZoPUZWVmg2dHFydFFlc3Z1X1BiQUxmUUEmZT0xNjE2NTIzNTQ4/e/6c/mHjbJTIzLfooznZsZ.mp4?loc=de:
                                                   
2021-03-22 19:19:08.967 T:4756    ERROR <general>: Open - <https://cdn.streambox.in/pd/kinopub/aWQ9Mzc2MDE1OzE1NTc4OTIxNDc7MTAzODQyNTg7MTYxNjQzNzE0OCZoPUZWVmg2dHFydFFlc3Z1X1BiQUxmUUEmZT0xNjE2NTIzNTQ4/e/6c/mHjbJTIzLfooznZsZ.mp4?loc=de> failed to open
2021-03-22 19:19:08.967 T:4756    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://video.kino.pub/play/69793]
2021-03-22 19:19:08.968 T:4756     INFO <general>: CVideoPlayer::OnExit()
2021-03-22 19:19:09.037 T:4750     INFO <general>: [video.kino.pub]: playback started
2021-03-22 19:19:09.139 T:2857     INFO <general>: CVideoPlayer::CloseFile()
2021-03-22 19:19:09.140 T:2857     INFO <general>: VideoPlayer: waiting for threads to exit
2021-03-22 19:19:09.141 T:2857     INFO <general>: VideoPlayer: finished waiting
2021-03-22 19:19:09.180 T:4750     INFO <general>: [video.kino.pub]: playback stopped
2021-03-22 19:19:09.196 T:4750     INFO <general>: [video.kino.pub]: resetting resume point
2021-03-22 19:19:09.199 T:4750     INFO <general>: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching/marktime?id=69793&video=1&time=0
2021-03-22 19:19:09.586 T:4750    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/xbian/.kodi/addons/video.kino.pub/resources/lib/player.py", line 97, in onPlayBackStopped
                                                       self.plugin.client("watching/marktime").get(data=data)
                                                     File "/home/xbian/.kodi/addons/video.kino.pub/resources/lib/client.py", line 50, in get
                                                       return self._make_request(request)
                                                     File "/home/xbian/.kodi/addons/video.kino.pub/resources/lib/client.py", line 40, in _make_request
                                                       response = json.loads(response.read())
                                                     File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

**Comment by quarckster** [comment]
`ERROR : CCurlFile::FillBuffer - Failed: Couldn't connect to server` Kodi не смог соединиться с CDN кинопаба. Пишите им в поддержку.
