### ISSUE TITLE
'Playback failed' when HLS stream type selected

### ISSUE THREAD

**Issue by achagaev** [quarckster/kodi.kino.pub#256]
'Playback failed' error pops-up when hls stream type selected.

1. Select 'Netherlands' or 'Russia' as CDN localization and 'HLS' as stream type
2. Try to navigate between folders or play any movie

Result is that add-on returns 'Playback failed' error. Expected behavior is to see movie or navigate to folder.
The same works when Netherlands/Russia selected as CDN localization and 'HLS4' as stream type.

Last time described logic with Netherlands and HLS type of streaming worked yesterday morning (February, 11th).

Logs from ~/.kodi/temp/kodi.log during issue reproduction:

```
2023-02-12 16:13:06.835 T:6731    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <class 'urllib.error.URLError'>
 Error Contents: <urlopen error timed out>
 Traceback (most recent call last):
   File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
     h.request(req.get_method(), req.selector, req.data, headers,
   File "/usr/lib/python3.9/http/client.py", line 1255, in request
     self._send_request(method, url, body, headers, encode_chunked)
   File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
     self.endheaders(body, encode_chunked=encode_chunked)
   File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
     self.send(msg)
   File "/usr/lib/python3.9/http/client.py", line 950, in send
     self.connect()
   File "/usr/lib/python3.9/http/client.py", line 1417, in connect
     super().connect()
   File "/usr/lib/python3.9/http/client.py", line 921, in connect
     self.sock = self._create_connection(
   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
     raise err
   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
     sock.connect(sa)
 socket.timeout: timed out
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
     plugin.run()
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 87, in run
     self.routing.dispatch(self.path)
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 71, in dispatch
     view_func(**kwargs)
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/main.py", line 288, in play
     playable_li = plugin.items.get_playable(item, season_index=si, index=i).playable_list_item
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 330, in playable_list_item
     path=self.media_url,
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 267, in media_url
     files = {f["quality"]: f["url"] for f in self.video_data["files"]}
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/utils.py", line 31, in __get__
     value = obj.__dict__[self.func.__name__] = self.func(obj)
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 506, in video_data
     return self.plugin.items.get_api_item(self.item_id)["videos"][0]
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 69, in get_api_item
     return self.plugin.client(f"items/{item_id}").get()["item"]
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/client.py", line 146, in get
     return self._make_request(request)
   File "/home/my_lovely_user/.kodi/addons/video.kino.pub/resources/lib/client.py", line 136, in _make_request
     response = self.opener.open(request, timeout=TIMEOUT)
   File "/usr/lib/python3.9/urllib/request.py", line 517, in open
     response = self._open(req, data)
   File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
     result = self._call_chain(self.handle_open, protocol, protocol +
   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
     result = func(*args)
   File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
     return self.do_open(http.client.HTTPSConnection, req,
   File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
     raise URLError(err)
 urllib.error.URLError: <urlopen error timed out>
 -->End of Python script error report<--
```
                            
Plugin version: 3.2.1
OS: raspbian bullseye Linux 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux

**Comment by achagaev** [comment]
Seems like the issue is not only in HLS. I had Russia+HLS4 combination configured and was able to watch film. After ~40 minutes i had to pause film but was unable to continue afterwards due to the same error with timeout.

**Comment by achagaev** [comment]
Seems like the issue is not only in HLS. I had Russia+HLS4 combination configured and was able to watch film. After ~40 minutes i had to pause film but was unable to continue afterwards due to the same error with timeout.

**Comment by quarckster** [comment]
I cannot reproduce it. Moreover, I don't think it's a plugin issue. It's more likely a networking problem.

**Comment by achagaev** [comment]
It's difficult to say if this is network issue or not, all other devices (android, browser on laptop) doesn't have this behavior and can be used without any issue by using the same home network. At the same time it doesn't exclude issue on server side.
Support team in Telegram redirects such type of requests to plugin developers if it appears. So this is the reason of raising new issue here.
I will keep the status updated.

**Comment by MaksymRD** [comment]
Здравстуйте, установлена версия плагина 3.4.1 и HLS4, не проигрывает любой контент который hevc(h.265) и также hdr, все доп. плагины установлены типа inputstream adaptive и т. д. Раньше через тип стриминга http всё было отлично, когда убрали его, то теперь получаеться смотреть только контент h.264 что для меня печально(

**Comment by quarckster** [comment]
Плагин тут не может помочь. Его задача предоставить интерфейс к кинопабу и вытащить ссылку на поток, который уже воспроизводится Kodi. Если ваше оборудование и/или операционная система не поддерживают hevc и hdr, то плагин тут бессилен.

**Comment by quarckster** [comment]
не уверен, что через http hevc отдавался, но это вопрос к владельцам кинопаба. Со своей стороны хочу сказать, что на моём Vero 4k+ hevc c hdr и 4k воспроизводятся через hls.

**Comment by achagaev** [comment]
Hello, i think we can close this ticket as soon as @quarckster and @MaksymRD are done with ongoing discussion.
Thank you.

**Comment by quarckster** [comment]
Выберите hls4.

**Comment by MaksymRD** [comment]
В том и проблема что когда выбираю hls4 ничего не воспроизводится с hevc и hdr
