### ISSUE TITLE
Plugin fail to play any video

### ISSUE THREAD

**Issue by top4ek** [quarckster/kodi.kino.pub#259]
**Describe the bug**
At Feb 14 plugin stopped working on Kodi 18 and 19. The same time I can browse content.

**To Reproduce**
1. Find any movie/episode
2. Start it.

**Actual results**
Error popup

**Expected behavior**
Video starts

**Additional context**
Stacktrace from 18.9 Media Center Kodi

```
2023-02-14 20:01:04.525 T:1329590496  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/items/18676
2023-02-14 20:01:06.524 T:1329590496  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=18676
2023-02-14 20:01:08.707 T:1329590496   ERROR: NEWADDON Unknown Video Info Key "time"
2023-02-14 20:01:09.716 T:1329590496   ERROR: Previous line repeats 18 times.
2023-02-14 20:01:09.716 T:1329590496 WARNING: CPythonInvoker(51, /home/osmc/.kodi/addons/video.kino.pub/addon.py): the python script "/home/osmc/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2023-02-14 20:17:58.177 T:1260384480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'http'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 70, in run
                                                self.routing.dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 63, in dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/main.py", line 414, in play
                                                ask_quality=plugin.settings.ask_quality,
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/utils.py", line 62, in get_mlink
                                                return files[natural_sort(files.keys())[-1]][stream_type]
                                            KeyError: 'http'
                                            -->End of Python script error report<--
2023-02-14 20:17:58.363 T:1260384480 WARNING: CPythonInvoker(53, /home/osmc/.kodi/addons/video.kino.pub/addon.py): the python script "/home/osmc/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
```

```
addon id="video.kino.pub" name="kino.pub" version="2.8.2" provider-name="quarckster">
  <requires>
    <import addon="xbmc.python" version="2.25.0"/>
    <import addon="script.module.inputstreamhelper" version="0.3.4"
```

**Comment by quarckster** [comment]
Please update the plugin to version 3.4.0.

**Comment by top4ek** [comment]
Thanks. Is there chance http mode will be reimplemented? I use it because of huge cache which helps against sudden backbone line fail(or internet at all), so at least i can finish current episode/movie. :)

**Comment by quarckster** [comment]
Nope, it was disabled on the server side. I just removed it as unsupported.

**Comment by top4ek** [comment]
Switched to hls(doesn't matter 1,2 or 4) and getting 
```
2023-02-15 15:50:25.903 T:1365242080   ERROR: AddOnLog: InputStream Adaptive: Cannot download /hls/<VERYLONGKEYHERE>.mp4/index-a2.m3u8?loc=nl
```
It plays well on web. Star trek ds9, episode 2, for example. (kino.pub/item/view/18676/s1e2). It's on Kodi 18. 19 will check later.

**Comment by quarckster** [comment]
First of all, please update the plugin, then try to install `inputstream adaptive` and `inspustream helper` plugins.

**Comment by top4ek** [comment]
Oh, my bad. I had 2.8.
Updated to 2.12.4, didn't help — same "Cannod download"

Also found funny moment: with that fail episode is marked as viewed.
Checked 3.4.0 on Kodi 19 — works ok.

**Comment by quarckster** [comment]
I'll figure out how to update version 2 of the plugin. Buy the only thing I can do there is just to remove http from the settings.

**Comment by top4ek** [comment]
Yes, I always had it installed and enabled. It doesn't work with disabled too. 
Tried hls, hls2 and hls4.
