### ISSUE TITLE
Unable to browse specific series. 

### ISSUE THREAD

**Issue by top4ek** [quarckster/kodi.kino.pub#266]
**Describe the bug**
Unable to browse series list of [History of the World: Part II](https://kino.pub/item/view/88066). Whereas every other series' ok.

**To Reproduce**
1. Go to 'I'm watching'
2. Enter into 'History of the World: Part II' series menu item.
3. Enter into season 1 menu item.

**Actual results**
Error popup appears.

**Expected behavior**
Getting the list of episodes.

**Screenshots**
```
2023-03-11 10:54:57.249 T:25823    INFO <general>: initializing python engine.
2023-03-11 10:54:57.249 T:508      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-03-11 10:54:57.249 T:508      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-03-11 10:55:00.944 T:25823   ERROR <general>: NEWADDON Unknown Video Info Key "time"
2023-03-11 10:55:01.117 T:25823   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 88, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 71, in dispatch
                                                       view_func(**kwargs)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/main.py", line 285, in season_episodes
                                                       xbmcplugin.addDirectoryItem(plugin.handle, episode.url, episode.list_item, False)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 294, in list_item
                                                       li = super().list_item
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 215, in list_item
                                                       video_info=self.video_info,
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 439, in video_info
                                                       "time": self.resume_time,
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 301, in resume_time
                                                       if self.watching_info["time"] == self.watching_info["duration"]:
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2023-03-11 10:55:01.262 T:25823    INFO <general>: Python interpreter stopped
2023-03-11 10:55:01.273 T:25821   ERROR <general>: GetDirectory - Error getting plugin://video.kino.pub/season_episodes/88066/1/
2023-03-11 10:55:01.309 T:448     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/season_episodes/88066/1/) failed
```

Plugin Version 3.4.1
Kodi 19.

**Comment by top4ek** [comment]
Looks like fixed on backend.
