### ISSUE TITLE
Ошибки при открытии любого пункта меню в плагине (PRiv2)

### ISSUE THREAD

**Issue by nikolaev-rd** [quarckster/kodi.kino.pub#295]
**Describe the bug**
Получаю ошибки в любом пункте меню KINO.PUB. Возможно дело в самом Кинопабе, может быть можно что-то настроить?

**To Reproduce**
1. Открываем плагин kino.pub последней версии 3.4.2 на Raspberry Pi v2 + LibreELEC (official): 11.0.0
2. Получаем ошибку, ничего не открывается

**Actual results**
Ниже кусок лога с ошибкой из `/storage/.kodi/temp/kodi.log` (конкретно это при попытке открыть Bookmarks):
```
2023-08-31 23:51:23.979 T:3063    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error [Errno 104] Connection reset by peer>
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
                                                     File "/usr/lib/python3.11/http/client.py", line 1282, in request
                                                     File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
                                                     File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
                                                     File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
                                                     File "/usr/lib/python3.11/http/client.py", line 975, in send
                                                     File "/usr/lib/python3.11/http/client.py", line 1454, in connect
                                                     File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
                                                     File "/usr/lib/python3.11/ssl.py", line 1075, in _create
                                                     File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
                                                   ConnectionResetError: [Errno 104] Connection reset by peer

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 88, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 71, in dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 319, in bookmarks
                                                       response = plugin.client("bookmarks").get()
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 153, in get
                                                       return self._make_request(request)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/client.py", line 142, in _make_request
                                                       response = self.opener.open(request, timeout=TIMEOUT)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 519, in open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
                                                   urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
                                                   -->End of Python script error report<--

2023-08-31 23:51:24.170 T:3062    error <general>: GetDirectory - Error getting plugin://video.kino.pub/bookmarks/
2023-08-31 23:51:24.214 T:678     error <general>: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/bookmarks/) failed
```

**Expected behavior**
Сломалось само в какой-то момент (ничего не обновлял / не менял), ожидается что само не должно ломаться.

**Screenshots**
—

**Additional context**
—

**Comment by nikolaev-rd** [comment]
Сброс авторизации не помогает

**Comment by stavultras** [comment]
У вас доступа нет к API кинопаба. Плагин вроде не причем.

**Comment by nikolaev-rd** [comment]
Действительно, когда issue заводил — работало с ноута, видимо в тот момент в браузере прокси был включен. Спасибо.

**Comment by nikolaev-rd** [comment]
Оказалось, что плагин не при чем, но доступа до АПИшки реально нет. @quarckster спасибо за [этот релиз](https://github.com/quarckster/kodi.kino.pub/releases/tag/3.5.0), где поменяли API URL, который доступен без проксей и прочих плясок!
