### ISSUE TITLE
Ошибка 403

### ISSUE THREAD

**Issue by top4ek** [quarckster/kodi.kino.pub#313]
**Describe the bug**
Два дня на двух машинах при любом действии выдаёт 403. С ВПН(личным и коммерческим), без ВПН.
В логах всегда похожее на 
`2023-11-24 10:17:15.646 T:31683 critical <general>: [video.kino.pub]: HTTPError. https://api.srvkp.com/v1/bookmarks. Code: 403. Exiting.`
Разлогин сделал всё ещё хуже — стектрейс ниже.

**To Reproduce**
1. Сходить в настройки, сбросить авторизацию
2. Открыть плуг, нажать на Activate device.

**Actual results**
```
2023-11-24 11:27:16.794 T:657     error <general>: EXCEPTION: Dialog not created.
2023-11-24 11:27:16.832 T:657     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: Dialog not created.
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 81, in _make_request
                                                       response = urllib.request.urlopen(
                                                     File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 523, in open
                                                       response = meth(req, response)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
                                                       response = self.parent.error(
                                                     File "/usr/lib/python3.9/urllib/request.py", line 561, in error
                                                       return self._call_chain(*args)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
                                                       result = func(*args)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 403: Forbidden

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 88, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 71, in dispatch
                                                       view_func(**kwargs)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/main.py", line 86, in login
                                                       plugin.auth.get_token()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 214, in get_token
                                                       self._activate()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 200, in _activate
                                                       resp = self._get_device_code()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 123, in _get_device_code
                                                       resp = self._make_request(payload)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 109, in _make_request
                                                       self._auth_dialog.close(cancel=True)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 51, in close
                                                       self._dialog.close()
                                                   RuntimeError: Dialog not created.
                                                   -->End of Python script error report<--
```
**Expected behavior**
Попап с кодом активации девайса.

**Additional context**
Kodi Media Center 20.2 (OSMC)
`<addon id="video.kino.pub" name="kino.pub" version="3.5.0" provider-name="quarckster">`

**Comment by arrybn** [comment]
Тоже столкнулся с такой же ошибкой
Аналогичное поведение, до разлогина перестали работать списки, типа I'm watching. Потом разлогинился, и после этого в логах 403

Коди запущен на Fire Stick 4k
При этом браузер с этого же устройства пускает на api.srvkp.com
Переустановка адд-она не помогла

**Comment by ivashin** [comment]
Аналогично. Не работает на Kodi 20.2 (CoreELEC 20.2-Nexus и Manjaro 23.1.0). Стек-трейсы идентичные

**Comment by quentincaffeino** [comment]
Анологично, похоже токены для плагина больше не действительны
https://github.com/quarckster/kodi.kino.pub/blob/2b701130fb5e611c6eeba5c57b1a4f98161b3e42/src/resources/lib/auth.py#L71-L72

**Comment by relictMarauder** [comment]
Токены действительны, но только для браузера. Я поменял User-Agent  и все заработало снова.
#315
