### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by superyarik** [quarckster/kodi.kino.pub#355]
**Describe the bug**
все работало, месяц не пользовался приложением, сейчас ловлю ошибку [Errno 104] Connection reset by peer
причем даже при попытке авторизации

```
2024-07-28 20:59:27.753 T:1358930656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.error'>
                                            Error Contents: [Errno 104] Connection reset by peer
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 76, in run
                                                self.routing.dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 63, in dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/main.py", line 74, in login
                                                plugin.auth.get_token()
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 209, in get_token
                                                self._activate()
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 192, in _activate
                                                resp = self._get_device_code()
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 114, in _get_device_code
                                                resp = self._make_request(payload)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 80, in _make_request
                                                urllib2.Request(self.OAUTH_API_URL), urllib.urlencode(payload)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "/usr/lib/python2.7/httplib.py", line 1137, in getresponse
                                                response.begin()
                                              File "/usr/lib/python2.7/httplib.py", line 448, in begin
                                                version, status, reason = self._read_status()
                                              File "/usr/lib/python2.7/httplib.py", line 404, in _read_status
                                                line = self.fp.readline(_MAXLINE + 1)
                                              File "/usr/lib/python2.7/socket.py", line 480, in readline
                                                data = self._sock.recv(self._rbufsize)
                                            error: [Errno 104] Connection reset by peer
```

коди 18, версия плагина 2.12.4

**Comment by stavultras** [comment]
Побанил ваш провайдер домен api кинопаба. Плагин тут ни при чём.

**Comment by superyarik** [comment]
для 2.12.4 какие-то варианты кроме vpn есть?

**Comment by stavultras** [comment]
> для 2.12.4 какие-то варианты кроме vpn есть?

Можете попробовать поправить сервер в client.py и auth.py, заменить https://api.service-kp.com/ на https://api.srvkp.com/

Если и его не побанили.

**Comment by quarckster** [comment]
Имеет ли смысл добавить настройку сервера, чтобы в код не лазить руками?

**Comment by quarckster** [comment]
> для 2.12.4 какие-то варианты кроме vpn есть?

Ещё можно прокси-сервер использовать.

**Comment by stavultras** [comment]
> Имеет ли смысл добавить настройку сервера, чтобы в код не лазить руками?

а этож legacy версия, не поддерживаемая. я руками правлю баги, если вылазят )

**Comment by quarckster** [comment]
> > Имеет ли смысл добавить настройку сервера, чтобы в код не лазить руками?
> 
> а этож legacy версия, не поддерживаемая. Я руками правлю баги, если вылазят - например, при отметке как просмотрено, лезла фатальная ошибка. В поддерживаемой версии я делал PR, а в этой поправил руками локально, по аналогии. На одной из приставок приходится использовать её, там kodi 18 и выше нет.

Ох, точно, я не обратил внимания. Тогда только VPN и хаки.
