### ISSUE TITLE
Не ставится из репозитория на Raspberry Pi

### ISSUE THREAD

**Issue by nikolaev-rd** [quarckster/kodi.kino.pub#47]
Раньше плагин ставился из репозитория и сразу работал, а сейчас не работает.
- Raspberry Pi 3
- LibreELEC 8.2.5 / 9.0.1 (ставил на чистую систему).

1. Скачиваю [repo.kino.pub.zip](http://plugins.service-kp.com/kodi/repo.kino.pub.zip)
2. Устанавливаю плагин из этого репозитория (версия плагина 2.6.2)
3. Получаю ошибку при открытии плагина, в логах дебага нашел такое:
```
2019-05-10 08:56:19.914 T:1937707680 WARNING: CAddonMgr: 'script.module.inputstreamhelper' required by 'video.kino.pub' is missing. Add-on may not function correctly
2019-05-10 08:56:20.018 T:1937707680   DEBUG: CAddonMgr: enabled video.kino.pub
2019-05-10 08:56:21.661 T:1656669040   DEBUG: PushCecKeypress - received key  b duration 0 (rep:0 size:0)
2019-05-10 08:56:21.661 T:1656669040   DEBUG: PushCecKeypress - added key  b
2019-05-10 08:56:21.705 T:1937707680   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2019-05-10 08:56:21.708 T:1937707680   DEBUG: CGUIMediaWindow::GetDirectory (plugin://video.kino.pub/)
2019-05-10 08:56:21.708 T:1937707680   DEBUG:   ParentPath = [addons://sources/video]
2019-05-10 08:56:21.711 T:1795597168   DEBUG: Thread waiting start, auto delete: false
2019-05-10 08:56:21.781 T:1656669040   DEBUG: PushCecKeypress - received key  b duration 120 (rep:0 size:0)
2019-05-10 08:56:21.781 T:1656669040   DEBUG: PushCecKeypress - ignored key  b
2019-05-10 08:56:21.798 T:1570763632   DEBUG: CAddonDatabase::SetLastUsed[video.kino.pub] took 90 ms
2019-05-10 08:56:21.799 T:1795597168   DEBUG: StartScript - calling plugin kino.pub('plugin://video.kino.pub/','15','','resume:false')
2019-05-10 08:56:21.799 T:1816114032   DEBUG: Thread LanguageInvoker start, auto delete: false
2019-05-10 08:56:21.800 T:1816114032    INFO: initializing python engine.
2019-05-10 08:56:21.800 T:1816114032   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/video.kino.pub/addon.py): start processing
2019-05-10 08:56:21.811 T:1937707680   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-05-10 08:56:21.877 T:1816114032   DEBUG: -->Python Interpreter Initialized<--
2019-05-10 08:56:21.877 T:1816114032   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/video.kino.pub/addon.py): the source file to load is "/storage/.kodi/addons/video.kino.pub/addon.py"
2019-05-10 08:56:21.877 T:1816114032   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/video.kino.pub/addon.py): setting the Python path to /storage/.kodi/addons/video.kino.pub:/usr/lib/python27.zip:/usr
/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0

2019-05-10 08:56:21.877 T:1816114032   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/video.kino.pub/addon.py): entering source directory /storage/.kodi/addons/video.kino.pub
2019-05-10 08:56:21.878 T:1816114032   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/video.kino.pub/addon.py): instantiating addon using automatically obtained id of "video.kino.pub" dependent on versi
on 2.25.0 of the xbmc.python api
2019-05-10 08:56:21.894 T:1816114032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named inputstreamhelper
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 2, in <module>
                                                from resources.lib import addonworker
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 5, in <module>
                                                import inputstreamhelper
                                            ImportError: No module named inputstreamhelper
                                            -->End of Python script error report<--
2019-05-10 08:56:21.894 T:1816114032   DEBUG: onExecutionDone(17, /storage/.kodi/addons/video.kino.pub/addon.py)
2019-05-10 08:56:21.897 T:1816114032    INFO: Python interpreter stopped
2019-05-10 08:56:21.898 T:1816114032   DEBUG: Thread LanguageInvoker 1816114032 terminating
```

**Но если скачать последний релиз и установить плагин из zip вручную - плагин запускается.**

**Comment by quarckster** [comment]
По какой-то причине зависимости не устанавливаются при обновлении из репы. В следующей версии это будет исправлено.

**Comment by nikolaev-rd** [comment]
Отличная новость! 
Потому что сейчас, как я понимаю, все кто пытаются установить плагин из репы — будут получать ошибку. Возможно стоит на время дополнить [инструкцию на сайте](https://kino.pub/plugin/kodi) вариантом установки из [zip-архива](https://github.com/quarckster/kodi.kino.pub/releases/download/2.6.2/video.kino.pub-2.6.2.zip) напрямую, без репы.

**Comment by nikolaev-rd** [comment]
> Отличная новость!
> Потому что сейчас, как я понимаю, все кто пытаются установить плагин из репы — будут получать ошибку. Возможно стоит на время дополнить [инструкцию на сайте](https://kino.pub/plugin/kodi) вариантом установки из [zip-архива](https://github.com/quarckster/kodi.kino.pub/releases/download/2.6.2/video.kino.pub-2.6.2.zip) напрямую, без репы.

Тупанул, есть такой пункт уже.

**Comment by quarckster** [comment]
Исправлено в https://github.com/quarckster/kodi.kino.pub/commit/b27d5d7e6b336170871e6667d28c46cfed1f756f
