### ISSUE TITLE
IndexError: list index out of range when season uploading in progress

### ISSUE THREAD

**Issue by achagaev** [quarckster/kodi.kino.pub#48]
**Describe the bug**
Currently new cartoons and new episodes are in progress with uploading to server.
Here is link:
https://kino.pub/item/view/50260/CHetvero-v-kube
The sequence of episodes (1 season) on web site is s1e1, s1e14, s1e15 etc.
As result it's not possible to watch the first season on TV with kodi and kino.pub plugin due to error below:
```
2019-05-21 17:16:38.899 T:1163064032   ERROR: NEWADDON Unknown Video Info Key "time"
2019-05-21 17:16:39.013 T:1163064032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/<name>/.kodi/addons/video.kino.pub/addon.py", line 17, in <module>
                                                main()
                                              File "/home/<name>/.kodi/addons/video.kino.pub/addon.py", line 13, in main
                                                addonworker.init()
                                              File "/home/<name>/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 659, in init
                                                ROUTES[request.path](**request.args)
                                              File "/home/<name>/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 280, in season_episodes
                                                watching_episode = watching_season["episodes"][episode["number"] - 1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-05-21 17:16:39.532 T:1163064032 WARNING: CPythonInvoker(336, /home/<name>/.kodi/addons/video.kino.pub/addon.py): the python script "/home/<name>/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2019-05-21 17:16:39.534 T:1143993056   ERROR: GetDirectory - Error getting plugin://video.kino.pub/view_season_episodes?id=50260&season_number=1
2019-05-21 17:16:39.536 T:1901716320   ERROR: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/view_season_episodes?id=50260&season_number=1) failed
2019-05-21 17:16:49.295 T:1163064032 WARNING: CPythonInvoker(337, /home/<name>/.kodi/addons/video.kino.pub/addon.py): the python script "/home/<name>/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

```
**To Reproduce**
1. Add new season to bookmarks. Season should be is in progress with uploading to server;
2. Start kino.pub plugin on Kodi and try to navigate to newly added season;
3. Notification with error will be displayed in top right corner.

**Actual results**
Can't watch newly added season

**Expected behavior**
Possibility to see list of eposides like on via web page.
**Screenshots**
Hard to create screenshot on TV

**Additional context**
```
addon.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="video.kino.pub" name="kino.pub" version="2.6.3" provider-name="quarckster">
  <requires>
    <import addon="xbmc.python" version="2.25.0"/>
    <import addon="script.module.inputstreamhelper" version="0.3.4" optional="true"/>
  </requires>
  <extension point="xbmc.python.pluginsource" library="addon.py">
    <provides>video</provides>
  </extension>
  <extension point="xbmc.addon.metadata">
    <summary>kino.pub - онлайн-кинотеатр.</summary>
    <platform>all</platform>
    <license>BSD-3-Clause</license>
    <source>https://github.com/quarckster/kodi.kino.pub</source>
    <assets>
      <icon>resources/icon.png</icon>
    </assets>
  </extension>
```

**Comment by fallenfuzz** [comment]
+1
