### ISSUE TITLE
Периодически слетает авторизация

### ISSUE THREAD

**Issue by vevsvevs** [quarckster/kodi.kino.pub#49]
Я видел упоминания о решении проблемы в описании предыдущего релиза, но к сожалению, в версии 2.6.3 она сохранилась. Ниже кусочек лога Kodi в момент возникновения проблемы (растянут на 3 минуты, т.к. я вышел из комнаты и не сразу заметил окно с запросом авторизации):
```
2019-05-26 00:50:47.813 T:4086174496   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-05-26 00:50:53.399 T:3379557232   ERROR: plugin://video.kino.pub. HTTPError. Code: 401. Message:
2019-05-26 00:50:54.319 T:3723031408   ERROR: Previous line repeats 1 times.
2019-05-26 00:50:54.319 T:3723031408  NOTICE: AddOnLog: PVR IPTV Archive Client: EPG Loaded.
2019-05-26 00:50:54.937 T:3379557232   ERROR: NEWADDON Unknown Video Info Key "time"
2019-05-26 00:51:02.137 T:3379557232   ERROR: Previous line repeats 15 times.
2019-05-26 00:51:02.137 T:3379557232 WARNING: CPythonInvoker(21, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2019-05-26 00:54:58.856 T:2994459504 WARNING: CPythonInvoker(19, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2019-05-26 00:54:59.800 T:3379557232   ERROR: NEWADDON Unknown Video Info Key "time"
2019-05-26 00:55:07.175 T:3379557232   ERROR: Previous line repeats 15 times.
```

**Comment by stavultras** [comment]
Подтверждаю. за последние 3-4 дня 3 раза реавторизовывался.

**Comment by twocolors** [comment]
kodi 18 нет авторизации 
```2018-06-22 14:18:06.181 T:1937715216   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2018-06-22 14:18:15.942 T:1584382832 WARNING: CPythonInvoker(3, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2018-06-22 14:18:23.032 T:1584382832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'URLError' object has no attribute 'code'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 17, in <module>
                                                main()
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 13, in main
                                                addonworker.init()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 659, in init
                                                ROUTES[request.path](**request.args)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 134, in login
                                                auth.reauth()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 89, in reauth
                                                self.do_login()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 195, in do_login
                                                status, resp = self.get_device_code()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 123, in get_device_code
                                                resp = self.request(self.OAUTH_API_URL, data)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 100, in request
                                                if e.code == 400:
                                            AttributeError: 'URLError' object has no attribute 'code'
                                            -->End of Python script error report<--
2018-06-22 14:18:23.831 T:1584382832 WARNING: CPythonInvoker(4, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2018-06-22 14:24:16.685 T:1799328624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'URLError' object has no attribute 'code'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 17, in <module>
                                                main()
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 13, in main
                                                addonworker.init()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 659, in init
                                                ROUTES[request.path](**request.args)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 134, in login
                                                auth.reauth()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 89, in reauth
                                                self.do_login()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 195, in do_login
                                                status, resp = self.get_device_code()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 123, in get_device_code
                                                resp = self.request(self.OAUTH_API_URL, data)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/authwindow.py", line 100, in request
                                                if e.code == 400:
                                            AttributeError: 'URLError' object has no attribute 'code'
                                            -->End of Python script error report<--
2018-06-22 14:24:17.220 T:1799328624 WARNING: CPythonInvoker(5, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
```

на 17 слитает после sleep, ошибка как в https://github.com/quarckster/kodi.kino.pub/issues/49#issue-448506971

**Comment by livinm** [comment]
слетает через день, подтверждаю

**Comment by vevsvevs** [comment]
Никакой системы нет, у меня авторизация слетела ещё всего один раз с момента открытия тикета 🤔

**Comment by twocolors** [comment]
хм, ждать фикс? @quarckster

**Comment by quarckster** [comment]
@twocolors пока не моуг ничего сделать

**Comment by vevsvevs** [comment]
Смущает такая бессистемность появления проблемы. С момента моего последнего комментария, авторизация слетела только раз.
Мой провайдер замечен в подсовывании наг-скрина с рекламой вместо запрошенного узла, не может ли это быть причиной?

**Comment by VyacheslavTeplyakov** [comment]
У меня система очень явная. Если смотреть сериал и в самом конце серии во время титров остановить серию, то активация тут же слетает.

**Comment by quarckster** [comment]
Возможно я нашёл причину бага:
```
2019-07-13 22:49:14.480 T:3350196960   ERROR: plugin://video.kino.pub. HTTPError. Code: 401. Message:
2019-07-13 22:49:14.481 T:3350196960   ERROR: Refresh data: {'client_secret': 'cgg3gtifu46urtfp2zp1nqtba0k2ezxh', 'grant_type': 'refresh_token', 'client_id': 'xbmc', 'refresh_token': '4z48hiy1vbdjyjptard91mlki8yiz568'}
2019-07-13 22:49:14.483 T:3425137376   ERROR: plugin://video.kino.pub. HTTPError. Code: 401. Message:
2019-07-13 22:49:14.484 T:3425137376   ERROR: Refresh data: {'client_secret': 'cgg3gtifu46urtfp2zp1nqtba0k2ezxh', 'grant_type': 'refresh_token', 'client_id': 'xbmc', 'refresh_token': '4z48hiy1vbdjyjptard91mlki8yiz568'}
2019-07-13 22:49:14.850 T:3350196960   ERROR: Get token response: {u'access_token': u'6hh0yjh26gqtjiw8zca3z4pd9iunrzg7', u'expires_in': 86400, u'refresh_token': u'0btqy7mumb45ol8mj4bqqjffs622b5u9'}
2019-07-13 22:49:14.855 T:3425137376   ERROR: Get token response: {u'status': 400, u'error': u'authorization_expired'}
2019-07-13 22:49:15.396 T:3350196960   ERROR: Get token response: {u'status': 400, u'error': u'authorization_pending'}
2019-07-13 22:54:20.603 T:3350196960   ERROR: Previous line repeats 115 times.
2019-07-13 22:54:20.603 T:3350196960   ERROR: Get token response: {u'status': 400, u'error': u'code_expired'}
2019-07-13 22:54:25.889 T:3350196960   ERROR: Previous line repeats 1 times.
2019-07-13 22:54:25.889 T:3350196960   ERROR: Get token response: {u'status': 400, u'error': u'bad_verification_code'}
2019-07-13 22:54:30.895 T:3350196960   ERROR: Previous line repeats 1 times.
2019-07-13 22:54:30.918 T:3350196960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SystemExit'>
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/player.py", line 67, in onPlayBackStopped
                                                KinoPubClient("watching/toggle").get(data=data)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/client.py", line 53, in get
                                                return self._make_request(request)
                                              File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/client.py", line 34, in _make_request
                                                sys.exit()
                                            SystemExit
                                            -->End of Python script error report<--

```
Похоже что иногда колбэк `onPlaybackStopped` по какой-то причине вызывается два раза подряд. В тот момент, когда токен истёк, посылается два запроса к API для его обновления с одинаковыми параметрами. Первый проходит успешно, токен обновляется, второй завершается неудачно, посколько refresh_token уже сменился, при этом значение `refersh_token` в настройках меняется на пустое значение, и регистарция слетает.

**Comment by vevsvevs** [comment]
Получается, можно в качестве решения просто не записывать пустое значение? По крайней мере, пока не станет понятна причина двойного вызова (если это не by-design в апях Kodi).

**Comment by quarckster** [comment]
@vevsvevs я всё ещё пытаюсь отследить баг, экспериментирую с фиксами, как только что-то получится, выпущу новую версию

**Comment by quarckster** [comment]
Вроде разобрался окончательно в чём причина. Когда заканчивается воспроизведение и токен уже протух, то посылается запрос на обновление токена. В то же время плагин пытается обновить список на экране, но так как токен протух, тоже посылает запрос на его обновление. Это происходит из-за того, что колбэки `onPlaybackStopped`, `onPlaybackEnded` и другие выполняются в отдельном потоке. То есть это состояние гонки. Как один из вариантов решения можно попробовать ввести переменную, которая будет блокировать запросы к API до тех пор, пока поток, начавший обновление токена, не завершит его. Пока я проверяю его у себя, но могу выложить в бету для тестирования.

**Comment by vevsvevs** [comment]
@quarckster отличные новости, безусловно было бы здорово поучаствовать в тестировании!

**Comment by aurodionov** [comment]
тоже имеет место быть на kodi 17 ,  бессистемно может слететь авторизация

**Comment by quarckster** [comment]
Можно потестировать эту версию https://github.com/quarckster/kodi.kino.pub/releases/tag/2.6.4-beta.1

**Comment by vevsvevs** [comment]
@quarckster, к сожалению, на этой версии проблема тоже сохранилась.

**Comment by aurodionov** [comment]
если не сложно в следующей версии добавьте мультфильмы отдельным пунктом

**Comment by achagaev** [comment]
подтверждаю, проблема на бете наблюдается

**Comment by zv2006** [comment]
2.6.4-beta.1 - проблема в наличии

**Comment by achagaev** [comment]
немного на 'поржать': ребёнок отменил активацию устройства и продолжил смотреть мульты.

**Comment by fallenfuzz** [comment]
Только что случилось после просмотра пары серий.
Выключил и плагин попросил добавить устройство.

**Comment by olsamurai** [comment]
Оно как-то вообще волнами. Иногда слетает по два раза в день, а сейчас уже две недели держится.

**Comment by quarckster** [comment]
У кого наблюдается ошибка установите эту версию плагина https://github.com/quarckster/kodi.kino.pub/releases/tag/2.6.4-beta.2. Я добавил больше отладочной информации. Когда в следующий раз аутентификация сбросится, прошу прислать мне логи.

**Comment by achagaev** [comment]
Поймал с утра, вот таймстемп:
2019-10-02 07:20:09.451 T:1172304608   ERROR: EXCEPTION Thrown (PythonToCppExcep
tion) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO M
EMORY LEAKS!
                                            Error Type: <type 'exceptions.System
Exit'>
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/video.
kino.pub/resources/lib/player.py", line 86, in onPlayBackEnded
                                                KinoPubClient("watching/toggle")
.get(data=data)
                                              File "/home/pi/.kodi/addons/video.
kino.pub/resources/lib/client.py", line 78, in get
                                                return self._make_request(reques
t)
                                              File "/home/pi/.kodi/addons/video.
kino.pub/resources/lib/client.py", line 59, in _make_request
                                                sys.exit()
                                            SystemExit
                                            -->End of Python script error report
<--
[log.tar.gz](https://github.com/quarckster/kodi.kino.pub/files/3682545/log.tar.gz)

**Comment by vevsvevs** [comment]
Тоже только что поймал.
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3682913/kodi.log)

**Comment by linoobs** [comment]
только что прилетело.
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3692467/kodi.log)

**Comment by quarckster** [comment]
Пожалуйста отправьте ещё логи с этой версией https://github.com/quarckster/kodi.kino.pub/releases/tag/2.6.4-beta.3

**Comment by vevsvevs** [comment]
Пожалуйста:
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3694704/kodi.log)

**Comment by quarckster** [comment]
Прошу потестировать эту версию https://github.com/quarckster/kodi.kino.pub/releases/download/2.6.4-beta.4/video.kino.pub-2.6.4-beta.4.zip. Похоже идея с блокировкой не работает в коди. Поэтому я поставил паузу в 5 секунд перед тем, как обновлять статус видео после окончания воспроизведения.

**Comment by vevsvevs** [comment]
К сожалению, теперь снова серии не отмечаются как просмотренные, пока не перезайдёшь в "папку".

**Comment by quarckster** [comment]
Ясно, попробую решить проблему по-другому

**Comment by quarckster** [comment]
@vevsvevs @linoobs @achagaev очередная попытка победить баг https://github.com/quarckster/kodi.kino.pub/releases/download/2.6.4-beta.5/video.kino.pub-2.6.4-beta.5.zip

**Comment by vevsvevs** [comment]
К сожалению, не помогло: [kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3721248/kodi.log)
Но болшое спасибо за ваши попытки :)

**Comment by quarckster** [comment]
По логу видно, что сосотояния гонки больше нет, но второй запрос всё равно использует старый токен, хотя предыдущий запрос обновил его.

**Comment by quarckster** [comment]
Нашёл ещё одну причину, из-за которой возникает баг. Kodi кэширует настройки, когда инициализируется класс `xbmcaddon.Addon`. Поэтому после обновления токена, новый запрос происходит со старым токеном.

**Comment by quarckster** [comment]
@vevsvevs https://github.com/quarckster/kodi.kino.pub/releases/tag/2.6.4-beta.6 надеюсь, что это последняя итерация.

**Comment by vevsvevs** [comment]
Эх, боюсь не последняя:
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3731100/kodi.log)

**Comment by linoobs** [comment]
Подтверждаю, вчера остановил просмотр, запросило авторизацию, усыпил комп, сегодня включилось как ни в чем не бывало. 
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3735927/kodi.log)

**Comment by quarckster** [comment]
Давайте ещё раз попробуем https://github.com/quarckster/kodi.kino.pub/releases/download/2.6.4-beta.7/video.kino.pub-2.6.4-beta.7.zip. На этот раз я попытлся обойти эту проблему. Теперь токен будет обновлятся, когда воспроизведение началось. Плагин высчитывает сколько времени осталось до того, как токен протухнет и обновляет его, если необходимо.

**Comment by quarckster** [comment]
@vevsvevs @linoobs @achagaev сбрасывается ли аутентификация в последней версии?

**Comment by vevsvevs** [comment]
@quarckster пока все отлично, наблюдаю дальше :) Большое спасибо!

**Comment by achagaev** [comment]
у меня последние три версии всё ОК, спасибо!

**Comment by quarckster** [comment]
Прошло пять дней, и ни у кого аутентификация не сбрасывалась. Наверное можно релизить.

**Comment by vevsvevs** [comment]
@quarckster жаль это говорить, но всё повторилось :(
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3810854/kodi.log)

**Comment by quarckster** [comment]
@vevsvevs судя по логу, токен не обновился когда воспроизведение началось. Измените функцию следующим образом, чтобы собрать больше информации:
``` 
@property
def should_refresh_token(self):
    logger.notice("Play duration {}".format(int(self.list_item.getProperty("play_duration"))
    logger.notice("Current time {}".format(int(time.time())
    logger.notice("Token expire {}".format(settings.access_token_expire)
    return int(time.time()) + int(self.list_item.getProperty("play_duration")) >= int(
        settings.access_token_expire
    )
```

**Comment by vevsvevs** [comment]
Сделано, жду повторения :)
Забыл уточнить, что после запроса активации опять помогла простая отмена - авторизация сохранилась. И просто мысли вслух: не может ли такое поведение быть связано с постановками на длительные паузы (иногда дольше самого видео) во время воспроизведения?

**Comment by quarckster** [comment]
Паузы тут не должны влиять, теперь токен должен обновляться, как только воспроизведение началось.

**Comment by VyacheslavTeplyakov** [comment]
у меня вчера слетала, какая актуальная версия? хочу проверить обновляется ли

**Comment by quarckster** [comment]
@VyacheslavTeplyakov последняя версия всегда здесь https://github.com/quarckster/kodi.kino.pub/releases/latest

**Comment by achagaev** [comment]
Раз уж пошла такая пляска: на последней бете (и в 2.7.0) по окончании просмотра периодически (~1 к 15) возвращает в пустую папку вместо папки со списком серий. Выход из папки в заход обратно решает проблему.

**Comment by quarckster** [comment]
@achagaev пожалуйста создайте отдельный баг.

**Comment by achagaev** [comment]
хорошо, на данный момент это воспринимается как регрешен от текущего багфикса.
Как поймаю, соберу логи и создам реквест.

**Comment by vevsvevs** [comment]
@quarckster наконец-то поймал. Опять простая отмена позволила сохранить авторизацию.
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/3847817/kodi.log)

**Comment by twocolors** [comment]
есть решение ?

**Comment by vladimir-poleh** [comment]
Для меня обновление плагина до 2,7,1 решило проблему с авторизацией.

**Comment by vladimir-poleh** [comment]
Пока за месяц не было ни одного разрыва с 2.7.1. Обновлюсь на 2.8.0 и продолжу наблюдение.

**Comment by quarckster** [comment]
Проблема ещё существует. Возможна ситуация, при которой активация сбросится, если видео на долгую паузу поставить.

**Comment by vladimir-poleh** [comment]
Правильный код для логирования в 2.8.0

```
    @property
    def should_refresh_token(self):
        self.plugin.logger.notice("Play duration {}".format(int(self.list_item.getProperty("play_duration"))))
        self.plugin.logger.notice("Current time {}".format(int(time.time())))
        self.plugin.logger.notice("Token expire {}".format(self.plugin.settings.access_token_expire))
        return int(time.time()) + int(self.list_item.getProperty("play_duration")) >= int(
            self.plugin.settings.access_token_expire
        )
```

**Comment by vladimir-poleh** [comment]
После долгой паузы получил запрос авторизации. Кнопка "Отмена" закрыла диалог, но я остался авторизованным.

```
2020-02-01 18:00:23.834 T:28732  NOTICE: [video.kino.pub]: playback ended
2020-02-01 18:00:23.939 T:28732  NOTICE: [video.kino.pub]: marking as watched
2020-02-01 18:00:23.948 T:28732  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching/toggle?status=1&season=1&video=3&id=8763
2020-02-01 18:00:24.428 T:27276  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/items/8763
2020-02-01 18:00:24.632 T:28732   ERROR: [video.kino.pub]: HTTPError. Code: 401.
2020-02-01 18:00:24.633 T:28732  NOTICE: [video.kino.pub]: refreshing token
2020-02-01 18:00:24.634 T:28732  NOTICE: [video.kino.pub]: sending payload {u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'refresh_token', u'client_id': u'xbmc', u'refresh_token': 'f1fcm56jw5l4ff3yrwvm7zcn8brpyra9'} to oauth api
2020-02-01 18:00:24.658 T:27276   ERROR: [video.kino.pub]: HTTPError. Code: 401.
2020-02-01 18:00:24.659 T:27276  NOTICE: [video.kino.pub]: refreshing token
2020-02-01 18:00:24.660 T:27276  NOTICE: [video.kino.pub]: sending payload {u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'refresh_token', u'client_id': u'xbmc', u'refresh_token': 'f1fcm56jw5l4ff3yrwvm7zcn8brpyra9'} to oauth api
2020-02-01 18:00:24.762 T:28732  NOTICE: [video.kino.pub]: sending payload {u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_code', u'client_id': u'xbmc'} to oauth api
2020-02-01 18:00:24.774 T:27276  NOTICE: [video.kino.pub]: refresh token - 9n2qjqm1lc4rp615adnz1kugn0l0tsx5; access token - g1ibm8kcdct4fj3neotvh16cXXXXXXXX; expires in - 86400
2020-02-01 18:00:24.774 T:27276  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/items/8763
2020-02-01 18:00:24.847 T:28732  NOTICE: [video.kino.pub]: getting a new device token
2020-02-01 18:00:24.847 T:28732  NOTICE: [video.kino.pub]: sending payload {u'code': u'2nc5xb3mrgj29v658yu5gp1jXXXXXXXX', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
2020-02-01 18:00:25.323 T:27276  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=8763
2020-02-01 18:00:25.573 T:27276   ERROR: NEWADDON Unknown Video Info Key "time"
2020-02-01 18:00:25.639 T:27276   ERROR: Previous line repeats 21 times.
2020-02-01 18:00:25.639 T:27276 WARNING: CPythonInvoker(25, C:\Users\ViSoR\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py): the python script "C:\Users\ViSoR\AppData\Roaming\Kodi\addons\video.kino.pub\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::DialogProgress
2020-02-01 18:00:29.951 T:28732  NOTICE: [video.kino.pub]: getting a new device token
2020-02-01 18:00:29.951 T:28732  NOTICE: [video.kino.pub]: sending payload {u'code': u'2nc5xb3mrgj29v658yu5gp1jXXXXXXXX', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
2020-02-01 18:00:35.043 T:28732  NOTICE: [video.kino.pub]: getting a new device token
2020-02-01 18:00:35.043 T:28732  NOTICE: [video.kino.pub]: sending payload {u'code': u'2nc5xb3mrgj29v658yu5gp1jXXXXXXXX', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
2020-02-01 18:00:40.137 T:28732  NOTICE: [video.kino.pub]: getting a new device token
2020-02-01 18:00:40.137 T:28732  NOTICE: [video.kino.pub]: sending payload {u'code': u'2nc5xb3mrgj29v658yu5gp1jXXXXXXXX', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
2020-02-01 18:00:45.235 T:28732  NOTICE: [video.kino.pub]: getting a new device token
2020-02-01 18:00:45.235 T:28732  NOTICE: [video.kino.pub]: sending payload {u'code': u'2nc5xb3mrgj29v658yu5gp1jXXXXXXXX', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
2020-02-01 18:00:50.331 T:28732  NOTICE: [video.kino.pub]: getting a new device token
2020-02-01 18:00:50.331 T:28732  NOTICE: [video.kino.pub]: sending payload {u'code': u'2nc5xb3mrgj29v658yu5gp1jXXXXXXXX', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
2020-02-01 18:00:55.428 T:28732  NOTICE: [video.kino.pub]: getting a new device token
2020-02-01 18:00:55.428 T:28732  NOTICE: [video.kino.pub]: sending payload {u'code': u'2nc5xb3mrgj29v658yu5gp1jXXXXXXXX', u'client_secret': u'cgg3gtifu46urtfp2zp1nqtbXXXXXXXX', u'grant_type': u'device_token', u'client_id': u'xbmc'} to oauth api
```

**Comment by vevsvevs** [comment]
За последние несколько месяцев проблема ни разу не повторилась. Правда CoreElec с очередным обновлением явно стал иначе отрабатывать возобновление воспроизведения после режима сна, может быть и это сыграло свою роль 🤷 Судя по активности в issue, других пользователей проблема тоже больше не беспокоит, закрываю.
