### ISSUE TITLE
Ошибка при запуске плагина

### ISSUE THREAD

**Issue by nikolaev-rd** [quarckster/kodi.kino.pub#50]
**Describe the bug**
Снова перестал работать плагин на LibreELEC 8.2.5 + Kodi 17.6.

**To Reproduce**
1. Ставим репозиторий v1.0.3.
2. Ставим плагин v2.6.3
3. Получаем ошибку при запуске

Также пробовал ставить плагин напрямую (v.2.6.2-2.6.3), без репозитория — не помогло.

**Actual results**
Ошибка при запуске плагина - см. лог ниже.

**Expected behavior**
Хотелось бы, чтобы плагин просто работал. Каждый раз что-то ломается, хотя на приставке ничего не трогал.

**Additional context**
Часть лога:
```
12:58:12.986 T:1945350144   ERROR: GetDirectory - Error getting plugin://video.kino.pub/
12:58:12.988 T:1945350144   ERROR: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/) failed
13:00:25.782 T:1513092000 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
13:00:25.783 T:1513092000 WARNING: Previous line repeats 1 times.
13:00:25.783 T:1513092000  NOTICE: LoadJpeg: unable to load /storage/.kodi/addons/skin.confluence/resources/fanart.jpg
13:01:51.800 T:1698911136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: bad marshal data (unknown type code)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 2, in <module>
                                                from resources.lib import addonworker
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/addonworker.py", line 5, in <module>
                                                import inputstreamhelper
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 14, in <module>
                                                import requests
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 112, in <module>
                                                from . import utils
                                            ValueError: bad marshal data (unknown type code)
                                            -->End of Python script error report<--
13:01:51.834 T:1945350144   ERROR: GetDirectory - Error getting plugin://video.kino.pub/
13:01:51.836 T:1945350144   ERROR: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/) failed
```

**Comment by nikolaev-rd** [comment]
Да, плагин InputStream вручную нашел и поставил. При попытке поставить из пункта в настройках плагина этого - тоже ошибка.

**Comment by nikolaev-rd** [comment]
[Весь лог](https://pastebin.com/uU63MqG3) после перезапуска приставки со всеми ошибками.

**Comment by nikolaev-rd** [comment]
На LibreELEC 9.0.2 + Kodi 18.2 — завелось.

**Comment by quarckster** [comment]
Плагин тут ни при чём:
```
File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 112, in <module>
from . import utils
ValueError: bad marshal data (unknown type code)
```
Этот кусок лога недвусмысленно говорит, что проблема в `requests` модуле. Как обходное решение отключить inputstream helper на  LibreELEC 8.2.5
