### ISSUE TITLE
Coreelec - закладки add to favorites. v2.8.0-beta1

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#59]
Поставил coreelec на миникс и вот:

`
2019-11-30 14:04:49.647 T:3311309632 WARNING: CPythonInvoker(14, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2019-11-30 14:04:53.787 T:3820987200  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/bookmarks
2019-11-30 14:04:54.550 T:3820987200 WARNING: CPythonInvoker(15, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2019-11-30 14:05:55.059 T:4091674640   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2019-11-30 14:06:11.870 T:3787416384 WARNING: CPythonInvoker(16, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2019-11-30 14:06:16.006 T:4091674640   ERROR: Control 51 in window 10025 has been asked to focus, but it can't
2019-11-30 14:06:16.352 T:3891180352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'Routing' object has no attribute 'path'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 68, in run
                                                self.routing.dispatch(self.path)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 65, in dispatch
                                                raise RoutingException('No route to path "{}"'.format(self.path))
                                            AttributeError: 'Routing' object has no attribute 'path'
                                            -->End of Python script error report<--
2019-11-30 14:06:16.426 T:3891180352 WARNING: CPythonInvoker(17, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2019-11-30 14:06:16.445 T:3787416384   ERROR: GetDirectory - Error getting plugin://video.kino.pub/bookmarks/
2019-11-30 14:06:16.455 T:4091674640   ERROR: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/bookmarks/) failed
`

Заранее спасибо.

**Comment by quarckster** [comment]
Какая версия плагина, какая версия kodi? Небходимы шаги для воспроизведения бага.

**Comment by fallenfuzz** [comment]
sorry, конечно.

coreelec 9.2.1 (коди 18,5)

Заходим в закладки в плагине, right click , add to favorites.
Выходим в главное меню коди, звездочка внизу, заходим в выше добавленный shortcut и всё - ошибка.

На Винде с коди 18,5 - работало.

Спасибо

**Comment by fallenfuzz** [comment]
@Limeone добрый день.
Буду очь. признателен если посмотришь.
Спасибо 😇

**Comment by Limeone** [comment]
У меня ошибка не воспроизводится

**Comment by fallenfuzz** [comment]
> У меня ошибка не воспроизводится

Странно, похоже это только на coreelec.
На винде и андроиде всё работает.
