### ISSUE TITLE
Не запускается плагин в LibreELEC 9.80 Kodi 19.0

### ISSUE THREAD

**Issue by buyfishya** [quarckster/kodi.kino.pub#80]
Плагин успешно ставится, но запускаться отказывается.
Пробовал с версией 2.6.4 и 2.8.1 , плагин отказывается запускаться.
==========================================================
часть лог файла с ошибкой ниже
2020-04-05 20:44:04.761 T:516   DEBUG: PushCecKeypress - received key  b duration 216
2020-04-05 20:44:04.865 T:487   DEBUG: ------ Window Deinit (Home.xml) ------
2020-04-05 20:44:04.865 T:487   DEBUG: FreeVisualisation() done
2020-04-05 20:44:05.056 T:487   DEBUG: ------ Window Init (MyVideoNav.xml) ------
2020-04-05 20:44:05.056 T:487    INFO: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2020-04-05 20:44:05.570 T:487   DEBUG: CGUIMediaWindow::GetDirectory (plugin://video.kino.pub/)
2020-04-05 20:44:05.570 T:487   DEBUG:   ParentPath = [plugin://video.kino.pub/]
2020-04-05 20:44:05.573 T:544   DEBUG: Thread waiting start, auto delete: false
2020-04-05 20:44:05.671 T:542   DEBUG: CAddonDatabase::SetLastUsed[video.kino.pub] took 100 ms
2020-04-05 20:44:05.673 T:487   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-04-05 20:44:05.744 T:544   DEBUG: StartScript - calling plugin kino.pub('plugin://video.kino.pub/','1','','resume:false')
2020-04-05 20:44:05.751 T:545   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-04-05 20:44:05.751 T:545    INFO: initializing python engine.
2020-04-05 20:44:05.752 T:545   DEBUG: CPythonInvoker(1, /storage/.kodi/addons/video.kino.pub/addon.py): start processing
2020-04-05 20:44:05.884 T:545   DEBUG: -->Python Interpreter Initialized<--
2020-04-05 20:44:05.884 T:545   DEBUG: CPythonInvoker(1, /storage/.kodi/addons/video.kino.pub/addon.py): the source file to load is "/storage/.kodi/addons/video.kino.pub/addon.py"
2020-04-05 20:44:05.884 T:545   DEBUG: CPythonInvoker(1, /storage/.kodi/addons/video.kino.pub/addon.py): setting the Python path to /storage/.kodi/addons/video.kino.pub:/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/lib/python3.7/site-packages:/usr/lib/python3.7/site-packages/gtk-2.0
2020-04-05 20:44:05.885 T:545   DEBUG: CPythonInvoker(1, /storage/.kodi/addons/video.kino.pub/addon.py): entering source directory /storage/.kodi/addons/video.kino.pub
2020-04-05 20:44:05.885 T:545   DEBUG: CPythonInvoker(1, /storage/.kodi/addons/video.kino.pub/addon.py): instantiating addon using automatically obtained id of "video.kino.pub" dependent on version 2.25.0 of the xbmc.python api
2020-04-05 20:44:06.218 T:545   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'urlparse'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 2, in <module>
                                                from resources.lib.main import plugin
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 24, in <module>
                                                from resources.lib.plugin import Plugin
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 6, in <module>
                                                from urlparse import parse_qsl
                                            ModuleNotFoundError: No module named 'urlparse'
                                            -->End of Python script error report<--
2020-04-05 20:44:06.219 T:545   DEBUG: onExecutionDone(1, /storage/.kodi/addons/video.kino.pub/addon.py)
2020-04-05 20:44:06.221 T:487   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-04-05 20:44:06.326 T:545    INFO: Python interpreter stopped
2020-04-05 20:44:06.326 T:545   DEBUG: Thread LanguageInvoker 2597876528 terminating
2020-04-05 20:44:06.335 T:544   ERROR: GetDirectory - Error getting plugin://video.kino.pub/
2020-04-05 20:44:06.335 T:544   DEBUG: Thread waiting 2832331568 terminating
2020-04-05 20:44:06.353 T:487   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-04-05 20:44:06.355 T:487   ERROR: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/) failed
2020-04-05 20:44:06.355 T:487   DEBUG: CGUIMediaWindow::GetDirectory ()
2020-04-05 20:44:06.355 T:487   DEBUG:   ParentPath = [plugin://video.kino.pub/]
2020-04-05 20:44:06.369 T:546   DEBUG: Thread waiting start, auto delete: false
2020-04-05 20:44:06.375 T:546   DEBUG: Thread waiting 2832331568 terminating
2020-04-05 20:44:06.513 T:547   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-04-05 20:44:06.533 T:547   DEBUG: Thread BackgroundLoader 2832331568 terminating

**Comment by quarckster** [comment]
Kodi 19.0 ещё не поддерживается, можете попробовать собрать плагин из ветки [py3](https://github.com/quarckster/kodi.kino.pub/tree/py3)
