### ISSUE TITLE
RoutingException: No route to path "/seasons/"

### ISSUE THREAD

**Issue by lespauI** [quarckster/kodi.kino.pub#85]
**Describe the bug**
Сериалы не открываются с виджета
**RoutingException: No route to path "/seasons/"**

**To Reproduce**
1. Добавить виджет в КОДИ с сериалами
2. открыть любой сериал
```
2020-05-25 20:40:39.550 T:2318381264   DEBUG: StartScript - calling plugin kino.pub('plugin://video.kino.pub/seasons/','232','','resume:false')
```

При этом фильмы или доку работают (наверное у них нет сезонов)
Вот этот запрос работает с виджета
```
2020-05-25 20:40:34.208 T:2450780368   DEBUG: StartScript - calling plugin 
kino.pub('plugin://video.kino.pub/watching','231','?reload=20200525173835','resume:false')
```
**Actual results**

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <class 'resources.lib.routing.RoutingException'>
 Error Contents: No route to path "/seasons/"
 Traceback (most recent call last):
   File "/home/homebridge/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
     plugin.run()
   File "/home/homebridge/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 70, in run
     self.routing.dispatch(self.path)
   File "/home/homebridge/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 65, in dispatch
     raise RoutingException('No route to path "{}"'.format(path))
 RoutingException: No route to path "/seasons/"
 -->End of Python script error report<--
```

**Expected behavior**
Откроется сериал

**Additional context**
Log
```
2020-05-25 20:40:39.550 T:2318381264   DEBUG: StartScript - calling plugin kino.pub('plugin://video.kino.pub/seasons/','232','','resume:false')
2020-05-25 20:40:39.551 T:2450780368   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-05-25 20:40:39.551 T:2450780368    INFO: initializing python engine.
2020-05-25 20:40:39.551 T:2450780368   DEBUG: CPythonInvoker(333, /home/homebridge/.kodi/addons/video.kino.pub/addon.py): start processing
2020-05-25 20:40:39.640 T:2973011040   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-05-25 20:40:39.730 T:2450780368   DEBUG: -->Python Interpreter Initialized<--
2020-05-25 20:40:39.730 T:2450780368   DEBUG: CPythonInvoker(333, /home/homebridge/.kodi/addons/video.kino.pub/addon.py): the source file to load is "/home/homebridge/.kodi/addons/video.kino.pub/addon.py"
2020-05-25 20:40:39.730 T:2450780368   DEBUG: CPythonInvoker(333, /home/homebridge/.kodi/addons/video.kino.pub/addon.py): setting the Python path to /home/homebridge/.kodi/addons/video.kino.pub:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/gtk-2.0
2020-05-25 20:40:39.730 T:2450780368   DEBUG: CPythonInvoker(333, /home/homebridge/.kodi/addons/video.kino.pub/addon.py): entering source directory /home/homebridge/.kodi/addons/video.kino.pub
2020-05-25 20:40:39.730 T:2450780368   DEBUG: CPythonInvoker(333, /home/homebridge/.kodi/addons/video.kino.pub/addon.py): instantiating addon using automatically obtained id of "video.kino.pub" dependent on version 2.25.0 of the xbmc.python api
2020-05-25 20:40:40.039 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.039 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.040 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.040 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.040 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.041 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.041 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.041 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.041 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.042 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.042 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.043 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.043 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.043 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.043 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.043 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.043 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.043 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.044 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.045 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.045 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.046 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.046 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.046 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.046 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.046 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.046 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.048 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.048 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.049 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.049 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.049 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.049 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.049 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.049 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.049 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.050 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.050 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.051 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.051 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.051 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.051 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.051 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.051 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.051 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.052 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.052 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.053 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.053 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.053 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.053 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.053 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.053 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.053 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.054 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.054 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.055 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.055 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.055 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.055 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.056 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.056 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.056 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.057 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.057 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.057 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.058 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.058 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.058 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.058 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.058 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.058 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.059 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.059 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.060 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.060 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.060 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.060 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.060 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.060 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.060 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.061 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.061 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.062 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.062 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.062 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.062 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.062 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.062 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.062 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.063 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.063 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.064 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.064 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.064 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.064 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.065 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.065 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.065 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.066 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.066 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.066 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.067 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.067 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.067 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.067 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.067 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.067 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.068 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting definitions
2020-05-25 20:40:40.068 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: trying to load setting definitions from old format...
2020-05-25 20:40:40.069 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: loading setting values
2020-05-25 20:40:40.069 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token) was not found.
2020-05-25 20:40:40.069 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.069 T:2450780368   DEBUG: CSettingsManager: requested setting (access_token_expire) was not found.
2020-05-25 20:40:40.069 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting access_token_expire. Creating a setting on-the-fly...
2020-05-25 20:40:40.069 T:2450780368   DEBUG: CSettingsManager: requested setting (refresh_token) was not found.
2020-05-25 20:40:40.069 T:2450780368   DEBUG: CAddonSettings[video.kino.pub]: failed to find definition for setting refresh_token. Creating a setting on-the-fly...
2020-05-25 20:40:40.087 T:2450780368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.routing.RoutingException'>
                                            Error Contents: No route to path "/seasons/"
                                            Traceback (most recent call last):
                                              File "/home/homebridge/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                plugin.run()
                                              File "/home/homebridge/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 70, in run
                                                self.routing.dispatch(self.path)
                                              File "/home/homebridge/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 65, in dispatch
                                                raise RoutingException('No route to path "{}"'.format(path))
                                            RoutingException: No route to path "/seasons/"
                                            -->End of Python script error report<--
2020-05-25 20:40:40.088 T:2450780368   DEBUG: onExecutionDone(333, /home/homebridge/.kodi/addons/video.kino.pub/addon.py)
2020-05-25 20:40:40.106 T:2973011040   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-05-25 20:40:40.122 T:2450780368 WARNING: CPythonInvoker(333, /home/homebridge/.kodi/addons/video.kino.pub/addon.py): the python script "/home/homebridge/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2020-05-25 20:40:40.122 T:2450780368    INFO: Python interpreter stopped
2020-05-25 20:40:40.122 T:2450780368   DEBUG: Thread LanguageInvoker 2450780368 terminating
2020-05-25 20:40:40.133 T:2318381264   ERROR: GetDirectory - Error getting plugin://video.kino.pub/seasons/
2020-05-25 20:40:40.133 T:2318381264   DEBUG: Thread waiting 2318381264 terminating
2020-05-25 20:40:40.138 T:2973011040   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-05-25 20:40:40.140 T:2973011040   ERROR: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/seasons/) failed
2020-05-25 20:40:40.140 T:2973011040   DEBUG: CGUIMediaWindow::GetDirectory ()
2020-05-25 20:40:40.140 T:2973011040   DEBUG:   ParentPath = [plugin://video.kino.pub/seasons/]
2020-05-25 20:40:40.144 T:2318381264   DEBUG: Thread waiting start, auto delete: false
2020-05-25 20:40:40.145 T:2318381264   DEBUG: Thread waiting 2318381264 terminating
2020-05-25 20:40:40.147 T:2318381264   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-05-25 20:40:40.155 T:2318381264   DEBUG: Thread BackgroundLoader 2318381264 terminating
2020-05-25 20:40:45.896 T:2973011040   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2020-05-25 20:41:09.550 T:2574602448   DEBUG: Thread JobWorker 2574602448 terminating (autodelete)
2020-05-25 20:41:09.550 T:2326773968   DEBUG: Thread JobWorker 2326773968 terminating (autodelete)
2020-05-25 20:41:09.550 T:2160316624   DEBUG: Thread JobWorker 2160316624 terminating (autodelete)
2020-05-25 20:41:46.093 T:2936000720   DEBUG: CAESinkPi:Drain delay:100ms now:0ms
2020-05-25 20:41:56.093 T:2936000720   DEBUG: CAESinkPi:Deinitialize
2020-05-25 20:41:56.094 T:2936000720   DEBUG: CAESinkPi:SetAudioProps hdmi_stream_channels 0 hdmi_channel_map 00000000
2020-05-25 20:41:56.102 T:2936000720   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.audio_render handle 0x9eb46d90
```

**Comment by quarckster** [comment]
О каких виджетах идёт речь?

**Comment by lespauI** [comment]
Я не уверен нативные это виджеты Коди или конкретного скина, я в коди новенький. 
Но у меня это скин https://github.com/jurialmunkey/skin.aura
И он умеет выводить виджетами на главную контент из адонов, в том числе из кинопаба. Выглядит примерно вот так
![image](https://user-images.githubusercontent.com/6555305/82839385-da8c3380-9ed7-11ea-86aa-db7bff7ef327.png)

**Comment by quarckster** [comment]
Скины кроме стандартного Estuary не поддерживаются, поскольку я ими н пользуюсь.

**Comment by lespauI** [comment]
если ты мне в двух словах напишешь как подебажить я сам починю, если ты не против конечно

**Comment by quarckster** [comment]
Я дебажу с помощью [webpdb](https://github.com/romanvm/kodi.web-pdb). Пулл-реквесты приветствуются.
